version 17
clear all
set more off

* Replace with the real master generated by build_empirical_master.py.
* No regression should run if core observations have not been imported.
local data "empirical_master.dta"
capture confirm file "`data'"
if _rc {
    display as error "Missing real empirical_master.dta; no simulated regression is allowed."
    exit 601
}
use "`data'", clear

isid stock_code year
foreach v in NQP_entropy patient_capital_total Size ListAge Lev ROA Growth CFO Top1 Board Indep Dual SOE {
    confirm variable `v'
}

encode stock_code, gen(firm_id)
xtset firm_id year

* The final analysis sample applies known ST/delisting flags and complete cases.
gen byte core_complete = !missing(NQP_entropy, patient_capital_total, Size, ListAge, Lev, ROA, Growth, CFO, Top1, Board, Indep, Dual, SOE)
keep if core_complete == 1

* Winsorization is applied to continuous variables only. Install winsor2 and
* reghdfe/ftools from their official SSC distributions before first use.
foreach v in NQP_entropy patient_capital_total Size ListAge Lev ROA Growth CFO Top1 Board Indep {
    winsor2 `v', cuts(1 99) replace
}

global controls Size ListAge Lev ROA Growth CFO Top1 Board Indep Dual SOE

* Baseline: firm FE + year FE; standard errors clustered by firm.
reghdfe NQP_entropy patient_capital_total $controls, absorb(firm_id year) vce(cluster firm_id)
estimates store baseline

* Temporal ordering / reverse-causality check.
reghdfe NQP_entropy L.patient_capital_total $controls, absorb(firm_id year) vce(cluster firm_id)
estimates store lag_x

* Alternative denominator measures, only if their actual coverage passes audit.
capture confirm variable patient_capital_a
if !_rc reghdfe NQP_entropy patient_capital_a $controls, absorb(firm_id year) vce(cluster firm_id)
capture confirm variable patient_capital_unrestricted_a
if !_rc reghdfe NQP_entropy patient_capital_unrestricted_a $controls, absorb(firm_id year) vce(cluster firm_id)

* Mechanism sequence. These regressions do not establish causal mediation by
* themselves; signs, confidence intervals and bootstrap indirect effects must be reported.
capture confirm variable FC_SA
if !_rc {
    reghdfe FC_SA patient_capital_total $controls, absorb(firm_id year) vce(cluster firm_id)
    reghdfe NQP_entropy patient_capital_total FC_SA $controls, absorb(firm_id year) vce(cluster firm_id)
}
capture confirm variable ICQ
if !_rc {
    reghdfe ICQ patient_capital_total $controls, absorb(firm_id year) vce(cluster firm_id)
    reghdfe NQP_entropy patient_capital_total ICQ $controls, absorb(firm_id year) vce(cluster firm_id)
}

* Expanded and boundary samples, PSM, placebo and alternative Y are separate
* robustness analyses and must not replace a failed baseline.
